# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default  # your self-hosted agent


variables:
  rg: 'home-assignment'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'myConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group $(rg) --template-file ./twoStorageAccounts.json --parameters firstStorageAccountName=pipelinefirst secondStorageAccountName=pipelinesecond
      az deployment group create --resource-group $(rg) --template-file ./linuxVM.json --parameters vmName=pipelineVM adminUsername=hanilzhome adminPasswordOrKey='P@ssword123!'

